language: node_js
node_js:
- node

cache:
  directories:
  - node_modules

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats python-pip python-setuptools
  - sudo pip install awscli

install:
- npm install --dd

script:
- npm run build --dd

deploy:
  provider: s3
  access_key_id: AKIAJRNJAWH5WTT2BZFA
  secret_access_key:
    secure: I/T4N0aiEmKuZn0m0y/qYHSiCJkOtsiVHrnROucAtM0R8u3rxReYujM14WVFaDMqLcf8L1Zb3LX5F5VHny8zzc0uTYEUbghyq2YTljMegHKW8CXHVoB1i3Mnz8kS7gRp97dtqHB+Bp6d5kZ7XR3P1jGeIDG2PE0flWkwknlCwpneKzCgzTcQmHwvMeYpJrMCCj8u298MqTn09P2gNUohN7p7bJ4BZwB+M6QYrqLPbMhH0iO77hZn6mogZ4Qqpeu4DsFXuoGyfJUtb3ntldEgb/y4dkWgGMMu1LbIXG3CwTPztRcZoHUTNMkvz9QCgUqio25rFkQ5tPl6uirj+3xgz9ASHRsIw5ONbeY0yhQRlB4+GU+TO8l0wKbjX3rI5hFIUGjsfc00Xi0CS284cPMI/0dyu6spQAjycMDojhGklLM4HDL4Ujq+A13YjpMG1zJWFsITRwNBZ1yzTdz+x90Hf7ZEXObM6xFVsBsFYAAFp5xLJ/gbsI5uEApXRr+VLCkJ3ikqZYMqGNcZ8l00aCLPVwikCFY4TDzdMmGxawVd+YAiP67aKpcys9ifTNb5/Vez/iUOHIuON6JSOeef0MkL1F/RWHRO34K4ccQOTCsEiuF+LbvmzueZsRqrmIwqX0fEK0ZG96DQeHKT+QAZUe2I/rF/1Y5/cqBt+fV0X+wRyxQ=
  bucket: api.itjobbikalmar.se
  local-dir: build
  acl: public_read
  region: eu-west-1
  skip_cleanup: true
  on:
    repo: im-peter/it-jobb-i-Kalmar-api

after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $API_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

branches:
  only:
  - master